image: maven:3.6.1-jdk-11-slim

stages:
- build
- deploy

before_script:
- 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
- eval $(ssh-agent -s)
- echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
- ssh-add <(echo "$SSH_PRIVATE_KEY")
- mkdir -p ~/.ssh
- chmod 600 ~/.ssh
- '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'


build-be:
    stage: build
    script:
        - echo "Building Backend"
        - mvn package -DskipTests=true -q
    artifacts:
        expire_in: 1 days
        paths:
            - target/project-1.0-SNAPSHOT.jar
    only: [master]

build-fe:
    stage: build
    image: node:10
    cache:
        paths:
          - node_modules/
    script:
        - echo "Building Frontend"
        - cd hotel
        - npm i --quiet
        - npm run build --quiet --prod
    artifacts:
      expire_in: 1 days
      paths:
          - hotel/dist
    only: [master]

deploy:
    stage: deploy
    script:
        - chmod +x ./deploy.sh
        - ./deploy.sh
        
    
