spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: test1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: hotel.team.five@gmail.com
    password: "!Test1234"
    protocol: smtp
    url: http://localhost:4200

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
            ssl.enable: true
          ssl.trust: smtp.gmail.com


logging:
  level:
    com.progmasters: debug
    org.springframework.web: info
    org.hibernate: error
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

cors-policies: http://localhost:4200, http://127.0.0.1:4200, http://[::1]:4200
